menu:
    # Index: /
    # Archive: /archives/
    Blog: /categories/blog
    Podcast: /categories/podcast
    GitHub: https://github.com/GaryXiongxiong
    Resume: /resume/
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2018
